-- Run this in your Supabase SQL Editor
-- Adds all onboarding fields to the clients table

ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS years_in_business TEXT,
  ADD COLUMN IF NOT EXISTS certifications TEXT,
  ADD COLUMN IF NOT EXISTS brands_used TEXT,
  ADD COLUMN IF NOT EXISTS services_offered TEXT,
  ADD COLUMN IF NOT EXISTS services_excluded TEXT,
  ADD COLUMN IF NOT EXISTS after_hours TEXT,
  ADD COLUMN IF NOT EXISTS emergency_response TEXT,
  ADD COLUMN IF NOT EXISTS charge_type TEXT,
  ADD COLUMN IF NOT EXISTS callout_fee TEXT,
  ADD COLUMN IF NOT EXISTS example_prices TEXT,
  ADD COLUMN IF NOT EXISTS minimum_job TEXT,
  ADD COLUMN IF NOT EXISTS free_quotes TEXT,
  ADD COLUMN IF NOT EXISTS payment_methods TEXT,
  ADD COLUMN IF NOT EXISTS payment_terms TEXT,
  ADD COLUMN IF NOT EXISTS working_hours_text TEXT,
  ADD COLUMN IF NOT EXISTS booking_lead_time TEXT,
  ADD COLUMN IF NOT EXISTS booking_preference TEXT,
  ADD COLUMN IF NOT EXISTS response_time TEXT,
  ADD COLUMN IF NOT EXISTS team_size TEXT,
  ADD COLUMN IF NOT EXISTS guarantees TEXT,
  ADD COLUMN IF NOT EXISTS unique_selling_point TEXT,
  ADD COLUMN IF NOT EXISTS common_questions TEXT,
  ADD COLUMN IF NOT EXISTS common_objections TEXT,
  ADD COLUMN IF NOT EXISTS ai_tone TEXT,
  ADD COLUMN IF NOT EXISTS ai_language TEXT,
  ADD COLUMN IF NOT EXISTS ai_response_style TEXT,
  ADD COLUMN IF NOT EXISTS ai_greeting TEXT,
  ADD COLUMN IF NOT EXISTS ai_escalation_triggers TEXT,
  ADD COLUMN IF NOT EXISTS ai_escalation_custom TEXT,
  ADD COLUMN IF NOT EXISTS ai_unhappy_customer TEXT,
  ADD COLUMN IF NOT EXISTS ai_always_do TEXT,
  ADD COLUMN IF NOT EXISTS ai_never_say TEXT,
  ADD COLUMN IF NOT EXISTS ai_sign_off TEXT,
  ADD COLUMN IF NOT EXISTS onboarding_complete BOOLEAN DEFAULT FALSE;
